### ISSUE TITLE
getting video frames question

### ISSUE THREAD

**Issue by CAOXINGWEN** [JunweiLiang/social-distancing-prediction#10]
Loading obj model...
obj model loaded.
Loading scene seg model...
scene seg model loaded.
Loading person appearance model...
person appearance model loaded.
Loading prediction model...
prediction model loaded.
1. Getting video frames...
Skipping /g/summervocation/papercode/social-distancing-prediction/test/test_video.mp4 due to Cannot open /g/summervocation/papercode/social-distancing-prediction/test/test_video.mp4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.90it/s]

Why can't the program read the test video？can you  slove this problem? thank you

**Comment by JunweiLiang** [comment]
Look at the code. It means your video cannot be opened by OpenCV: https://github.com/JunweiLiang/social-distancing-prediction/blob/master/code/inference/main.py#L377

**Comment by CAOXINGWEN** [comment]
> Look at the code. It means your video cannot be opened by OpenCV: https://github.com/JunweiLiang/social-distancing-prediction/blob/master/code/inference/main.py#L377

**Comment by CAOXINGWEN** [comment]
> Look at the code. It means your video cannot be opened by OpenCV: https://github.com/JunweiLiang/social-distancing-prediction/blob/master/code/inference/main.py#L377

thanks,I checked the program,  my path is not set correctly. I have solved it myself. Thank you for your work
