### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by satikurup** [JunweiLiang/social-distancing-prediction#11]
after running "ffmpeg -framerate 30.0 -i test_video/test_video_F_%08d.jpg test_video.mp4"
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, image2, from 'test_video/test_video_F_%08d.jpg':
  Duration: 00:00:15.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 30 tbn, 30 tbc
File 'test_video.mp4' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x563f2a3c3e00] using SAR=1/1
[libx264 @ 0x563f2a3c3e00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x563f2a3c3e00] profile High, level 4.0
[libx264 @ 0x563f2a3c3e00] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'test_video.mp4':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuvj420p(pc), 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.107.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=  450 fps=8.6 q=-1.0 Lsize=    8196kB time=00:00:14.90 bitrate=4506.3kbits/s speed=0.286x    
video:8190kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.075094%
[libx264 @ 0x563f2a3c3e00] frame I:2     Avg QP:20.29  size:330540
[libx264 @ 0x563f2a3c3e00] frame P:116   Avg QP:22.04  size: 54447
[libx264 @ 0x563f2a3c3e00] frame B:332   Avg QP:27.49  size:  4244
[libx264 @ 0x563f2a3c3e00] consecutive B-frames:  0.7%  0.4%  7.3% 91.6%
[libx264 @ 0x563f2a3c3e00] mb I  I16..4:  1.6% 80.0% 18.4%
[libx264 @ 0x563f2a3c3e00] mb P  I16..4:  0.2%  0.6%  0.3%  P16..4: 46.2% 16.8% 15.2%  0.0%  0.0%    skip:20.6%
[libx264 @ 0x563f2a3c3e00] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8: 35.8%  1.0%  0.3%  direct: 0.3%  skip:62.6%  L0:40.4% L1:58.0% BI: 1.6%
[libx264 @ 0x563f2a3c3e00] 8x8 transform intra:70.8% inter:66.8%
[libx264 @ 0x563f2a3c3e00] coded y,uvDC,uvAC intra: 85.5% 87.6% 33.8% inter: 10.2% 14.8% 1.1%
[libx264 @ 0x563f2a3c3e00] i16 v,h,dc,p: 16% 43% 14% 28%
[libx264 @ 0x563f2a3c3e00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12% 16% 19%  8%  7%  6%  8%  9% 14%
[libx264 @ 0x563f2a3c3e00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 15% 13% 10%  7%  8%  7% 10%  9%
[libx264 @ 0x563f2a3c3e00] i8c dc,h,v,p: 47% 24% 23%  7%
[libx264 @ 0x563f2a3c3e00] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x563f2a3c3e00] ref P L0: 64.5% 15.0% 16.3%  4.2%
[libx264 @ 0x563f2a3c3e00] ref B L0: 90.6%  8.3%  1.1%
[libx264 @ 0x563f2a3c3e00] ref B L1: 94.2%  5.8%
[libx264 @ 0x563f2a3c3e00] kb/s:4472.58

where can i find the output video

**Comment by JunweiLiang** [comment]
Please post the full error messages.
