### ISSUE TITLE
实时性

### ISSUE THREAD

**Issue by Poul1George** [JunweiLiang/social-distancing-prediction#13]
请问这个代码可以做到摄像头实时检测吗

**Comment by JunweiLiang** [comment]
当然可以，参考这个[配置](https://github.com/JunweiLiang/social-distancing-prediction#speed)下的处理速度，但是代码需要改成视频流处理而不是一整个视频。

**Comment by Poul1George** [comment]
您好，感谢您的回复！我在复现《social-distancing-prediction》的代码时，出现了出现了既没有报错也没有出结果的问题。方便解答是什么原因吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junwei ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 下午5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JunweiLiang/social-distancing-prediction] 实时性 (Issue #13)





 
当然可以，参考这个配置下的处理速度，但是代码需要改成视频流处理而不是一整个视频。

**Comment by JunweiLiang** [comment]
没遇到过，而且是哪一步出错？这样说谁知道是什么原因?
