### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU 	 [[node model_0/pool0/max_pooling2d/MaxPool (defined at /home/fmorenovr/anaconda3/envs/distance/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

### ISSUE THREAD

**Issue by fmorenovr** [JunweiLiang/social-distancing-prediction#15]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
	 [[node model_0/pool0/max_pooling2d/MaxPool (defined at /home/fmorenovr/anaconda3/envs/distance/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Why is this happening_??

**Comment by JunweiLiang** [comment]
This means Tensorflow-GPU is not properly installed. This code base needs to be run on GPUs.

**Comment by fmorenovr** [comment]
I already setup all dependencies .. Im using GPU (tested on tensorflow 1.15 and 1.15.2). But error still appears ...

**Comment by JunweiLiang** [comment]
Try following [this](https://stackoverflow.com/questions/62475762/tensorflow-1-15-cannot-detect-gpu-with-cuda10-1) to test whether your python is using tensorflow-gpu. See [this](https://github.com/VisualComputingInstitute/SiamR-CNN/issues/3) for a related issue.

**Comment by fmorenovr** [comment]
Thanks, I solved. But now appears another one ...

tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(8355840, 1), b.shape=(1, 4), m=8355840, n=4, k=1
	 [[{{node model_0/fpn/upsample_lat3/Tensordot/MatMul}}]]
	 [[model_0/fastrcnn_predictions/map/while/body/_1/Neg_1/_1307]]
  (1) Internal: Blas GEMM launch failed : a.shape=(8355840, 1), b.shape=(1, 4), m=8355840, n=4, k=1
	 [[{{node model_0/fpn/upsample_lat3/Tensordot/MatMul}}]]
	 
	 just after to the step " 2. Object detection & tracking... "

**Comment by JunweiLiang** [comment]
Does a simple Google search help? This seems to be related to not having enough GPU memory.

**Comment by fmorenovr** [comment]
Thanks, I solved it.
