### ISSUE TITLE
Can display ade,fde?

### ISSUE THREAD

**Issue by miraclesheephaha** [JunweiLiang/social-distancing-prediction#21]
The visualization has been successfully run, but I would like to ask whether social-distancing-prediction can display the ade and fde of the model for the input video, looking forward to your reply, thank you.

**Comment by JunweiLiang** [comment]
No, the visualization does not include showing ADE/FDE. You can check out the test script from the [Next project](https://github.com/google/next-prediction/blob/master/TESTING.md#step-3-test-the-models---actev) to modify it.

**Comment by miraclesheephaha** [comment]
ok thanks for your reply

**Comment by miraclesheephaha** [comment]
I would like to ask which github the model was trained on?（next-models_nokp）
