### ISSUE TITLE
Getting the following error. The url followed by wget is invalid

### ISSUE THREAD

**Issue by adithya6aj** [JunweiLiang/social-distancing-prediction#5]
D:\Code\social-distancing-prediction-master>bash scripts/download_models.sh
scripts/download_models.sh: line 7: wget: command not found
scripts/download_models.sh: line 9: wget: command not found
scripts/download_models.sh: line 11: wget: command not found
scripts/download_models.sh: line 13: wget: command not found
tar (child): person_cnn.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'person_cnn.tgz': No such file or directory
tar (child): prediction_model.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'prediction_model.tgz': No such file or directory

**Comment by JunweiLiang** [comment]
The urls are valid. Your output says you don't have wget.
