### ISSUE TITLE
activity prediction question

### ISSUE THREAD

**Issue by isaryo** [JunweiLiang/social-distancing-prediction#8]
Hi,
I want to plot the activity prediction.so, I tried to [this](https://github.com/JunweiLiang/social-distancing-prediction/blob/ee34744e5bc91d18d73453dd0cbd5957b2e31578/code/inference/main.py#L1151).
And, getting the following error.NameError: name ['this_pred'](https://github.com/JunweiLiang/social-distancing-prediction/blob/ee34744e5bc91d18d73453dd0cbd5957b2e31578/code/inference/main.py#L1155) is not defined.

**Comment by JunweiLiang** [comment]
It is renamed `pred_data`. Also, please give the repo a star if you are using it.

**Comment by isaryo** [comment]
OK. I take the repo a star.
How is [this](https://github.com/JunweiLiang/social-distancing-prediction/blob/ee34744e5bc91d18d73453dd0cbd5957b2e31578/code/inference/main.py#L1164) used?
What is the code to add?

**Comment by isaryo** [comment]
Specifically, I want to know what code do we add to draw the activity prediction.
Almost unchanged [this](https://github.com/JunweiLiang/social-distancing-prediction/blob/ee34744e5bc91d18d73453dd0cbd5957b2e31578/code/inference/main.py#L1199) to draw the activity prediction, We find the closest number `prob_sum` for `act_pred`?

**Comment by JunweiLiang** [comment]
That is specifically for social distancing warnings. `act_pred` is already a sorted list of [activity_name, activity_score], all you need to do is to plot the top 1 activity name!! Use `cv2.putText`!!! Why is it so hard?!
